-- Create table for the instructors
CREATE TABLE INSTRUCTOR{
ID_INSTRUCTOR INTEGER PRIMARY KEY,
INSTRUCTOR_NAME VARCHAR(5),
PASSWORD VARCHAR(20) NOT NULL
};

-- Create table for the students
CREATE TABLE STUDENT{
ID_STUDENT INTEGER PRIMARY KEY,
STUDENT_NAME VARCHAR(5),
ID_GROUP INTEGER,
PASSWORD VARCHAR(20) NOT NULL
};

-- Create table for the evalution
CREATE TABLE EVALUATION{
ID_EVALUATION SERIAL PRIMARY KEY,
ID_EVALUATOR INTEGER,
ID_EVALUATEE INTEGER,
ID_GROUP INTEGER REFERENCES STUDENT(ID_GROUP),
FOREIGN KEY (ID_EVALUATOR) REFERENCES STUDENT(ID_STUDENT),
FOREIGN KEY (ID_EVALUATEE) REFERENCES STUDENT(ID_STUDENT),
UNIQUE (ID_EVALUATOR, ID_EVALUATEE)
};

-- Create an index to order by STUDENT_NAME
CREATE INDEX IDX_STUDENT_NAME ON STUDENT(STUDENT_NAME);

-- Create an index to order by INSTRUCTOR_NAME
CREATE INDEX IDX_INSTRUCTOR_NAME ON INSTRUCTOR(INSTRUCTOR_NAME);

-- Create an index to order by ID_GROUP
CREATE INDEX IDX_ID_GROUP ON STUDENT(ID_GROUP);
