CREATE TABLE INSTRUCTOR{
ID_INSTRUCTOR INTEGER PRIMARY KEY,
INSTRUCTOR_NAME VARCHAR(5)
};

CREATE TABLE STUDENT{
ID_STUDENT INTEGER PRIMARY KEY,
STUDENT_NAME VARCHAR(5),
ID_GROUP INTEGER
};

CREATE TABLE EVALUATION{
ID_EVALUATION SERIAL PRIMARY KEY,
ID_EVALUATOR INTEGER,
ID_EVALUATEE INTEGER,
ID_GROUP INTEGER REFERENCES STUDENT(ID_GROUP),
FOREIGN KEY (ID_EVALUATOR) REFERENCES STUDENT(ID_STUDENT),
FOREIGN KEY (ID_EVALUATEE) REFERENCES STUDENT(ID_STUDENT),
PRIMARY KEY (ID_EVALUATOR, ID_EVALUATEE)
};