name: CI/CD Pipeline

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define the jobs to run in the pipeline
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version that matches your project

      # Install jest and supertest as dev dependencies
      - name: Install jest and supertest
        run: npm install jest supertest --save-dev

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # # Run tests
      - name: Run tests
        run: npm test
